[tool.poetry]
name = "datagateway-api"
version = "0.1.0"
description = "ICAT API to interface with the DataGateway"
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/ral-facilities/datagateway-api"
repository = "https://github.com/ral-facilities/datagateway-api"
authors = ["Matthew Richards <matthew.richards@stfc.ac.uk>"]

[tool.poetry.dependencies]
python = "^3.6"
Flask-RESTful = "0.3.7"
SQLAlchemy = "1.3.8"
PyMySQL = "0.9.3"
Flask-Cors = "3.0.8"
apispec = "3.3.0"
flask-swagger-ui = "3.25.0"
PyYAML = "5.1.2"
python-icat = "0.17.0"
suds-community = "^0.8.4"

[tool.poetry.dev-dependencies]
pip-tools = "5.3.1"
Faker = "2.0.2"
black = "19.10b0"
flake8 = "^3.8.4"
flake8-bandit = "^2.1.2"
flake8-black = "^0.2.1"
flake8-bugbear = "^20.1.4"
flake8-import-order = "^0.18.1"
safety = "^1.9.0"
flake8-builtins = "^1.5.3"

[tool.poetry.scripts]
datagateway-api = "datagateway_api.src.main:run_api"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
