name: Coverage
on:
  pull_request:
  push:
    branches:
      - master
      - feature/code-coverage-#167
jobs:
  coverage:
    runs-on: ubuntu-16.04
    name: Code Coverage
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
        architecture: x64
    - name: Checkout DataGateway API
      uses: actions/checkout@v2
      with:
        path: datagateway-api

    - name: Install Nox
      run: pip install nox==2020.8.22
    - name: Install Poetry
      run: pip install poetry==1.1.4
    - name: Get & upload code coverage data
      run: nox -s coverage
